public class DataModel{
        public String domainName { get; set; }
		public String email_sha256 { get; set; }
		public String evar1 { get; set; } // pageName
		public String evar99 { get; set; } // email_sha256
		public String pageName { get; set; }
		public String pageURL { get; set; }
		public String reportSuiteID { get; set; }
		public String userGUID { get; set; }
		public String visitorid { get; set; }
}